# test:
#   service: Disk
#   root: <%= Rails.root.join("tmp/storage") %>

# local:
#   service: Disk
#   root: <%= Rails.root.join("storage") %>

local:
  service: Disk
  root: <%= File.join(Dir.pwd, "storage") %>

